import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'

import { cn } from '@/lib/utils'
// import { Navbar } from './components/navbar'
import { Footer } from './components/footer'
import { ButtonFloatWttp } from './components/Buttons'
import { NavbarDropdown } from './components/navbardropdown'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-200 via-emerald-300 to-green-600 font-sans antialiased',
          fontSans.variable,
        )}
      >
        <NavbarDropdown />
        {children}
        <Footer />
        <ButtonFloatWttp />
      </body>
    </html>
  )
}
